name: "Pipeline DEV"

on:
  push:
    branches: [ dev ]

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws-region: "us-east-2"
      aws-state-s3-bucket: "fabiosantos.info-pipeline-github-terraform"
      aws-lock-table: "fabiosantos.info-pipeline-github-lock-table"
      aws-assume-role-arn: "arn:aws:iam::038462754550:role/pipeline_github_terraform"